services:
  - type: web
    name: neptune-gui
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: NEPTUNE_COMPILE_URL
        value: https://woo-25824--neptune-compute-api.modal.run
    healthCheckPath: /api/v2/health
